[tool.poetry]
name = "ditree"
version = "0.0.1"
description = "Dependency Injector with dataclass integration"
authors = ["Anton Demkin <antondemkin@yandex.ru>"]
license = "MIT"
readme = "README.rst"

[tool.poetry.dependencies]
python = [
    "^3.9",
    "^3.10",
    "^3.11",
    "^3.12",
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
